# Generated by Django 4.0.6 on 2022-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0002_auto_20201128_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
