# Generated by Django 3.2 on 2022-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmovie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
