# Generated by Django 4.0.6 on 2023-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplayer', '0002_uploadmovie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='movie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
