# Generated by Django 4.0.6 on 2023-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplayer', '0003_alter_uploadmovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
    ]
